apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: enable-service-api-auth-hpa
  namespace: unitgenius
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: enable-service-api-auth-deployment
  minReplicas: 1
  maxReplicas: 1
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  # - type: Resource
  #   resource:
  #     name: memory
  #     target:
  #       type: Utilization
  #       averageUtilization: 90
