apiVersion: v1
kind: Service
metadata:
  name: unitgenius-rabbitmq-service
  namespace: unitgenius
spec:
  selector:
    app: unitgenius-rabbitmq
  ports:
  - protocol: TCP
    port: 5672
    targetPort: 5672
