apiVersion: apps/v1
kind: Deployment
metadata:
  name: unitgenius-rabbitmq-deployment
  namespace: unitgenius
  labels:
    app: unitgenius-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unitgenius-rabbitmq
  template:
    metadata:
      labels:
        app: unitgenius-rabbitmq
    spec:
      containers:
      - name: unitgenius-rabbitmq
        image: rabbitmq:latest
        ports:
        - containerPort: 5672
        env:
        - name: RABBITMQ_DEFAULT_USER
          valueFrom:
            secretKeyRef:
              name: unitgenius-rabbitmq-secret
              key: username
        - name: RABBITMQ_DEFAULT_PASS
          valueFrom:
            secretKeyRef:
              name: unitgenius-rabbitmq-secret
              key: password
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 250m
            memory: 2Gi
        
        
        

      

 

